### ISSUE TITLE
migrated to Pyvisa1.6.1 from 1.5, getting Timeout Issue in query();

### ISSUE THREAD

**Issue by malli-1729** [hgrecco/pyvisa#109]
Hi,

I am using PyVISA to control DSOX-3024A from Keysight.
I am using dsoObj(DSO Object created from ResourceManager.get_instrument()).ask() command to ask like *IDN? to DSO in PyVISA 1.5 ---> changed to dsoObj.query("*IDN?") in PyVISA 1.6.1.
When i am running full code in PySCRIPTER most of the time code fails at dsoObj.query("*IDN?") saying Timeout. Image is attached.
When i try in command prompt line by line it is working properly.....
![visa_io_error_timeout](https://cloud.githubusercontent.com/assets/10267074/5523313/bbe7348a-89ec-11e4-9477-2ecdd94a2fdb.png)

**Comment by hgrecco** [comment]
I am closing this for now. Feel free to reopen if necessary.
