### ISSUE TITLE
Timeout with read/query using TCPIP Sockets

### ISSUE THREAD

**Issue by jonnojohnson** [hgrecco/pyvisa#110]
I'm getting a timeout error when trying to read or query using a Socket connection. I've only tried this on one instrument. Could you confirm on another instrument? I tested the same instrument using a TCPIP:Instr connection and it works fine.
Using the latest Master code from Github.

**Comment by hgrecco** [comment]
It works for me with the simulated devices in Lantz. Be careful that a device that works as with  INSTR does not necessarily work with SOCKET. INSTR has more information.

**Comment by hgrecco** [comment]
Is  this still a problem?
