### ISSUE TITLE
could not make pyvisa work for Anaconda 64 in windows 7

### ISSUE THREAD

**Issue by V33RA** [hgrecco/pyvisa#125]
Hi I'm new to python, I'm trying to communicate with the instruments. I installed PyVISA from https://github.com/hgrecco/pyvisa/zipball/master and ran the following in Anaconda command prompt

$ python setup.py install

Then I typed "import visa" in the spyder console and it seemed to go through, then I typed rm = visa.ResourceManager(), and I see the following error.:

![image](https://cloud.githubusercontent.com/assets/11453560/6634079/b887f5b8-c920-11e4-9896-d54c22f572b5.png)

Other things I did: I checked the versions, Anaconda version I'm using is 64 bit and NI-VISA 14.0 documentation says it can support both 32 and 64 bit in windows 7. And I ran [python -c "from pyvisa import util; util.get_debug_info()"] too (took this from another issue posted) and the output was:

![image](https://cloud.githubusercontent.com/assets/11453560/6634095/e44a6b4a-c920-11e4-9ebe-fe91f739aecd.png)

I don't know what i'm doing wrong. Am I missing to provide a path and how to provide? Any solution?

Thanks in advance.

**Comment by hgrecco** [comment]
No problem. I am closing this Feel free to reopen.
