### ISSUE TITLE
pyvisa 1.6.1 can not set stopbits

### ISSUE THREAD

**Issue by StachowP** [hgrecco/pyvisa#127]
Hi,
i have a problem with pyvisa 1.6.1 and the RS232 setting.
my device requires two stop bits. But the syntax in phyton "device.stop_bits=2" returns an error "ValueError: 2 is an invalid value for attribute VI_ATTR_ASRL_STOP_BITS, should be a <enum 'StopBits'>".

**Comment by hgrecco** [comment]
You should use the constants In the current dev version,
```
from pint import constants
device.stop_bits = constants.VI_ASRL_STOP_TWO
````
or 
```
from pint import constants
device.stop_bits = constants.StopBits.two
```

In any case, we should improve the error message.

**Comment by StachowP** [comment]
I installed the pint 0.6 version. Now the Syntax "from pint Import constants" returns an error "ImportError: cannot import name constants" Did i build-in the wrong Pint version?

**Comment by hgrecco** [comment]
Sorry. it should have said 
```
from visa import constants
```
or (in older pyvisa versions)
```
from pyvisa import constants
```

**Comment by StachowP** [comment]
Still does not work.
File "C:/Workspaces/spyder/test/helloagilent.py", line 2, in <module>
    from visa import constants
ImportError: cannot import name constants

**Comment by hgrecco** [comment]
As mentioned before, `from visa` only works in more recent versions of pyvisa

**Comment by hgrecco** [comment]
I am closing this. Feel free to reopen.
