### ISSUE TITLE
leaking memory

### ISSUE THREAD

**Issue by lupien** [hgrecco/pyvisa#135]
The method list_resources of the class ResourceManager in the file pyvisa/highlevel.py leaks memory.

The problem is that lib.find_resources returns a new handle in find_list. That handle is deleted but never closed, therefore memory attached to the new handle leaks.
Repeated calls to the method will produce a visible memory increase in the python process.
The fix is to do
  lib.close(find_list)
before returning (but after the find_next).

**Comment by hgrecco** [comment]
Thanks! This prompted me to implemente a long desired change. I still need to test it.

**Comment by hgrecco** [comment]
I think this is fixed now.
