### ISSUE TITLE
Timeout expired before operation completed.

### ISSUE THREAD

**Issue by fromage88** [hgrecco/pyvisa#161]
When trying to conntect to mt DG1022A I get a timeout error.
Other devices work perfectly.

> import visa
> visa.log_to_screen()
> rm = visa.ResourceManager() print
> rm.list_resources()
> print rm.list_resources()[0]
> my_instrument = rm.open_resource(rm.list_resources()[0])
> print  my_instrument.query('*IDN?')

I have posted the output here
[output](http://pastebin.com/byyRj8eG)

With the VISA interactive control there ist not this problem.

I would be glad if someone could help me.

**Comment by jayich** [comment]
I am getting a similar error at the moment with a Rigol DG1022.  The errors in the post above look the same as what I am seeing.  Help here would be greatly appreciated.  If more information is needed, please let me know.

**Comment by jayich** [comment]
Update, I can do the following (rigol is the ope_resource).

```python
>>> rigol.write('*IDN?')
(7L, <StatusCode.success: 0>)
>>> rigol.read()
u'RIGOL TECHNOLOGIES,DG1022 ,DG1D150900538,,00.03.00.09.00.02.11\n'
```

**Comment by fromage88** [comment]
I had wrong syntax somewhere else in the code. after fixing that in worked

**Comment by hgrecco** [comment]
Thanks for writing back.

**Comment by WilliamGenetelli** [comment]
I had the same issue. From another [blog](https://btbm.ch/rigol-dg1022-control-with-python-pyvisa/), someone suggested to add a delay between sending the commands to avoid the timeout. 

```python
rigol = rm.open_resource('USB0::0x1AB1::0x0588::DG1D120300062::INSTR') #  use the write and read methods (instead of query) with a little delay before the read
rigol.write('*IDN?')
time.sleep(0.01)
print(rigol.read())
```

```
>>> RIGOL TECHNOLOGIES,DG1022 ,DG1D120300062,,00.02.00.06.00.02.05
```
