### ISSUE TITLE
how to solve the error: windowsError(2,'Le fichier sp\xe9cifi\xe9 est introuvable sublime text 2 

### ISSUE THREAD

**Issue by marie15** [hgrecco/pyvisa#182]
Hi everybody, I tried to use input in python 2.7.4 but I faced this error: EOFError: EOF when reading a line. So I choose to use sublimeREPL to be able to use input statement. So I go to tools->SublimeREPL->python-run current file, but Unfortunately, this error appeared:      
windowsError(2,'Le fichier sp\xe9cifi\xe9 est introuvable

I look for the solution for days :(.. Can you help me please!!!

**Comment by hgrecco** [comment]
This issue board is related to PyVISA. For problems with Python or Sublime
Editor try the mailing lists or issue boards corresponding to those
projects.
