### ISSUE TITLE
how to control multiple instruments using pyvisa

### ISSUE THREAD

**Issue by aebk2015** [hgrecco/pyvisa#183]
I am trying to control multiple instruments using pyvisa. The following code works for single instrument but if multiple instruments is connected it returns the version of the same instrument but not all.

I want to implement "if" or "while" statement before self.Open=self.rm.open_resource(self.key) making sure it opens the same instrument only one time and so moves to the next available devices in self.list_of_devices but I couldn't find is_open option for the list_resources.

Is there any way I can fulfil this task. Considering I am new to python and pyvisa, I am eager to hear any feedback about my overall approach as well.

import visa

class Controllers(object):
def __init__(self):
    self.rm=visa.ResourceManager()
    self.list_of_devices=self.rm.list_resources()
    number_of_devices=len (number_of_devices)
    for device in range (number_of_devices):
       self.key=number_of_devices[device]
       self.Open=self.rm.open_resource(self.key)

def write_read(self, command):
    self.command=command
    self.Open.write(self.command)
    return (self.Open.read())       

def get_version(self):
    return self.write_read("1VE")

class CONEX(Controllers):
def __init__(self):
    super(CONEX,self).__init__()
    self.Open=self.rm.open_resource(self.key,baud_rate=921600, write_termination='\r\n')

my_device1=CONEX() 
my_device2=CONEX()

**Comment by hgrecco** [comment]
Just store in a dictionary the result of open_resource.
