### ISSUE TITLE
readtheDocs link to "edit on github" broken

### ISSUE THREAD

**Issue by JMoVS** [hgrecco/pyvisa#193]
Accessing pyvisa.readthedocs.org and trying to get to github trhough the "edit on github" badge in the upper right corner doesn't work on any page. Resulting links are eg 
https://github.com/hgrecco/pyvisa/blob/42ddd395231ae05fd99ddadf04a4a4cbf562a59c/docs/architecture.rst
which will throw a 404.

**Comment by hgrecco** [comment]
This was a problem in read the docs: https://github.com/rtfd/readthedocs.org/issues/1637
