### ISSUE TITLE
list resources not working for USB Raw devices

### ISSUE THREAD

**Issue by totpic** [hgrecco/pyvisa#198]
I want to know the identification number of the USB RAW devices I have connected to the computer.
So I write:
![pyvisa](https://cloud.githubusercontent.com/assets/10036095/11556090/d2cf81e8-99a4-11e5-99ff-b033b0d188a3.png)

The USB RAW device I have connected is now listed, but NI-MAX can find it.
![max](https://cloud.githubusercontent.com/assets/10036095/11556095/d9311ab0-99a4-11e5-9646-56ba42ab99aa.png)

I try with diferent USB RAW devices and PyVisa is not listing them.

Machine Details:
   Platform ID:    Windows-7-6.1.7601-SP1
   Processor:      Intel64 Family 6 Model 58 Stepping 9, GenuineIntel

Python:
   Implementation: CPython
   Executable:     C:\Python27\python.exe
   Version:        2.7.10
   Compiler:       MSC v.1500 32 bit (Intel)
   Bits:           32bit
   Build:          May 23 2015 09:40:32 (#default)
   Unicode:        UCS2

PyVISA Version: 1.7

Backends:
   ni:
      Version: 1.7 (bundled with PyVISA)
      #1: C:\WINDOWS\system32\visa32.dll:
         found by: auto
         bitness: 32
         Vendor: National Instruments
         Impl. Version: 14680064
         Spec. Version: 5243904
      #2: C:\WINDOWS\system32\visa32.dll:
         found by: auto
         bitness: 32
         Vendor: National Instruments
         Impl. Version: 14680064
         Spec. Version: 5243904

**Comment by hgrecco** [comment]
`list_resources` follows the same semantics as NI-VISA which is showing only INSTR devices by default. You can list all resources in the following way:
```python
>>> rm.list_resources('?*')
```

**Comment by totpic** [comment]
Thanks, It is working now.

**Comment by NPellet** [comment]
Helped for me to connect to my GPIB-USB-HS USB to GPIB converter.

Thanks !

(But it should be made clearer in the docs, this is an NI product...)
