### ISSUE TITLE
Use librevisa as a backend

### ISSUE THREAD

**Issue by jhol** [hgrecco/pyvisa#200]
The open source [librevisa](http://www.librevisa.org/) library would be a much better backend than NI-VISA. It should be pretty simple to integrate and would allow pyvisa users to access VISA with a complete free software stack.

**Comment by hgrecco** [comment]
You can actually select the library that you want just giving the right dll or so as an argument. Sadly, librevisa is far for complete. So it is not really a drop in replacement for NI-VISA. To have a complete free software stack we are developing pyvisa-py which is a python backend for pyvisa using pyusb, pyserial and linux-gpib.
