### ISSUE TITLE
reading binary data from a serial device

### ISSUE THREAD

**Issue by sidneycadot** [hgrecco/pyvisa#93]
Hi,

I am implementing a binary protocol over a serial port.

Reading a predetermined number of bytes from a serial device (using read_raw) appears to throw an exception if the read succeeds:

"""
C:\Users\ra-arcf20\sidney\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-pa
ckages\pyvisa\ctwrapper\functions.py:1569: VisaIOWarning: VI_SUCCESS_MAX_CNT (St
atusCode.success_max_count_read): The number of bytes transferred is equal to th
e requested input count. More data may be available.
  ret = library.viRead(session, buffer, count, byref(return_count))
Traceback (most recent call last):
  File "TestThorlabsMFF102MShutter.py", line 89, in <module>
    shutter.setPosition(p)
  File "TestThorlabsMFF102MShutter.py", line 70, in setPosition
    queryPos = self.getPosition()
  File "TestThorlabsMFF102MShutter.py", line 79, in getPosition
    (msgId, msgParam1, msgParam2, msgDst, msgSrc, msgData) = self._readMessage()

  File "TestThorlabsMFF102MShutter.py", line 33, in _readMessage
    header = self._visaResource.read_raw(6)
  File "C:\Users\ra-arcf20\sidney\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib
\site-packages\pyvisa\resources\messagebased.py", line 281, in read_raw
    chunk, status = self.visalib.read(self.session, size)
  File "C:\Users\ra-arcf20\sidney\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib
\site-packages\pyvisa\ctwrapper\functions.py", line 1569, in read
    ret = library.viRead(session, buffer, count, byref(return_count))
  File "C:\Users\ra-arcf20\sidney\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib
\site-packages\pyvisa\ctwrapper\highlevel.py", line 145, in _return_handler
    raise errors.VisaIOError(ret_value)
pyvisa.errors.VisaIOError: VI_ERROR_TMO (StatusCode.error_timeout): Timeout expi
red before operation completed.
"""

Is there a way to just have the call succeed?

**Comment by hgrecco** [comment]
This is fixed now. Feel free to reopen.

**Comment by moritzj29** [comment]
just for reference (for people as myself who are stumbling across such old issues): The new command your are probably looking for is `read_bytes`.
see #301 #315  #329
